import type { Metadata } from "next";
import Link from "next/link";
import { ArrowDown, ArrowRight, DatabaseIcon, ServerIcon, SparkIcon } from "@/components/ui/icons";
import { ConceptChain } from "@/components/lesson/concept-chain";
import { LessonPager } from "@/components/lesson/lesson-pager";
import { CacheArchitectureLab, CachePlacementLab, DesignCacheGame } from "@/components/labs/cache-architecture-labs";
import { Reveal } from "@/components/ui/reveal";
import { SectionHeading } from "@/components/ui/section-heading";

export const metadata:Metadata={title:"Cache Architectures & Redis",description:"Explore cache-aside, read-through, write-through, write-back, local caches, and shared Redis."};
const toc=[["01","Ownership","#ownership"],["02","Patterns","#patterns"],["03","Redis","#redis"],["04","Challenge","#challenge"]] as const;
export default function CacheArchitecturesPage(){return <article className="lesson-page cache-architecture-page"><section className="cache-architecture-hero page-shell"><div className="lesson-breadcrumb"><Link href="/#learning-map">Learning map</Link><span>/</span><b>Performance</b><span>/</span><span>Chapter 09</span></div><ConceptChain current="09"/><div className="topic-hero-grid"><div><p className="eyebrow"><span/>CACHE OWNERSHIP · 30 MIN LAB</p><h1>Fast copy.<br/><em>Clear owner.</em></h1><p className="lesson-deck">Caching helped. Now decide where the copy lives, who loads it, and what a successful write actually means.</p><a className="text-link" href="#ownership">Follow a read <ArrowDown/></a></div><div className="ownership-hero"><div><small>APPLICATION</small><ServerIcon/><b>Who owns the logic?</b></div><ArrowRight/><div><small>CACHE</small><SparkIcon/><b>Copy · memory</b></div><ArrowRight/><div><small>DATABASE</small><DatabaseIcon/><b>Source of truth</b></div><strong>READ · WRITE · FAILURE</strong></div></div></section><nav className="chapter-nav" aria-label="Chapter sections"><div className="page-shell"><span>CHAPTER 09</span><div>{toc.map(([n,l,h])=><a href={h} key={n}><small>{n}</small>{l}</a>)}</div></div></nav>
<section className="lesson-section page-shell" id="ownership"><Reveal><SectionHeading eyebrow="01 · CACHE OWNERSHIP" title="The arrows define the architecture." copy="Cache-aside keeps loading logic in the application. Read-through moves miss loading behind a cache provider. Write-through waits for the durable store; write-back acknowledges before the later flush."/></Reveal><div className="pattern-primer"><div><span>ASIDE</span><b>App loads misses</b><p>Common and explicit. Empty keys pay the full read path.</p></div><div><span>READ THROUGH</span><b>Provider loads misses</b><p>The application asks one abstraction; the provider owns population.</p></div><div><span>WRITE THROUGH</span><b>Persist before ACK</b><p>Reads stay fresh at the cost of synchronous write work.</p></div><div><span>WRITE BACK</span><b>ACK before persist</b><p>Fast writes spend durability and recovery complexity.</p></div></div></section>
<section className="lesson-section lesson-section--wide" id="patterns"><div className="page-shell"><Reveal><SectionHeading eyebrow="02 · PLAY WITH THE PATH" title="Read it. Write it. Break it." copy="Switch architectures, perform reads and writes, then fail the cache. No pattern is ranked universally; each makes ownership and failure promises."/></Reveal><Reveal delay={0.08}><CacheArchitectureLab/></Reveal></div></section>
<section className="lesson-section page-shell" id="redis"><Reveal><SectionHeading eyebrow="03 · SHARED STATE" title="Redis gives the fleet one fast meeting place." copy="Redis is an in-memory data system often used for caching, sessions, counters, rate-limit state, TTL data, and more. Here we focus on the shared-cache role—not CLI commands."/></Reveal><div className="redis-use-grid"><div><b>KEY / VALUE</b><code>product:42 → ₹999</code></div><div><b>SESSION</b><code>session:abc → user 10</code></div><div><b>COUNTER</b><code>views:video → 8,204</code></div><div><b>TTL DATA</b><code>otp:123 → expires</code></div></div><Reveal delay={0.08}><CachePlacementLab/></Reveal></section>
<section className="lesson-section lesson-section--wide" id="challenge"><div className="page-shell"><Reveal><SectionHeading eyebrow="04 · APPLY IT" title="Design the cache." copy="Choose architecture from read/write shape, ownership, freshness, durability, and fleet topology."/></Reveal><Reveal delay={0.08}><DesignCacheGame/></Reveal></div></section>
<section className="takeaway-section"><div className="page-shell"><Reveal><SectionHeading eyebrow="CACHE ARCHITECTURE SUMMARY" title="A fast answer still needs an owner."/></Reveal><div className="topic-summary-grid"><div><span>01</span><b>Cache aside</b><p>The application loads requested misses.</p></div><div><span>02</span><b>Write policy</b><p>Choose when a write becomes acknowledged.</p></div><div><span>03</span><b>Redis</b><p>Shared memory coordinates an application fleet.</p></div><div><span>04</span><b>Failure</b><p>Fallback must not overwhelm the source of truth.</p></div></div><div className="source-note"><span>SOURCE MAPPING</span><p>Derived from <a href="https://github.com/ChetanAmritanshu/High-Level-Design/blob/main/09_Cache_Architectures_and_Redis.docx" target="_blank" rel="noreferrer"><code>09_Cache_Architectures_and_Redis.docx</code></a>. The source establishes cache placement, cache-aside, Redis basics, distributed ownership, source-of-truth reasoning, and failure trade-offs.</p></div><LessonPager previous={{number:"08",title:"Caching Fundamentals",href:"/learn/caching"}} next={{number:"10",title:"Cache Invalidation & Advanced Failures",href:"/learn/cache-invalidation-failures",copy:"See what happens when fast copies become wrong or collapse under load."}}/><Link className="back-to-map" href="/#learning-map"><ServerIcon/> Return to the learning map <ArrowRight/></Link></div></section></article>}
