import type { Metadata } from "next";
import Link from "next/link";
import { ArrowDown, ArrowRight, ServerIcon } from "@/components/ui/icons";
import { ConceptChain } from "@/components/lesson/concept-chain";
import { LessonPager } from "@/components/lesson/lesson-pager";
import { EdgeRoleComparison, GatewayPipelineLab, GuardBackendGame, ProxyPerspective } from "@/components/labs/gateway-labs";
import { Reveal } from "@/components/ui/reveal";
import { SectionHeading } from "@/components/ui/section-heading";

export const metadata: Metadata={title:"Reverse Proxy & API Gateway",description:"Understand reverse proxies, API gateways, and load balancers through an interactive request pipeline."};
const toc=[["01","Entry layer","#entry"],["02","Proxy","#proxy"],["03","Gateway","#gateway"],["04","Compare","#compare"],["05","Challenge","#challenge"]] as const;
export default function GatewayPage(){return <article className="lesson-page gateway-page"><section className="gateway-hero page-shell"><div className="lesson-breadcrumb"><Link href="/#learning-map">Learning map</Link><span>/</span><b>Networking</b><span>/</span><span>Chapter 07</span></div><ConceptChain current="07"/><div className="topic-hero-grid"><div><p className="eyebrow"><span/>THE SERVICE EDGE · 27 MIN LAB</p><h1>One front door.<br/><em>Many decisions.</em></h1><p className="lesson-deck">Load balancers, reverse proxies, and API gateways can all sit before servers. The useful distinction is the question each layer is primarily answering.</p><a className="text-link" href="#entry">Follow a request <ArrowDown/></a></div><div className="gateway-hero-card"><div><small>CLIENT REQUESTS</small>{["/users","/orders","/payments","/images"].map((path)=><code key={path}>{path}</code>)}</div><ArrowRight/><span><b>ENTRY LAYER</b><small>route · protect · forward</small></span><ArrowRight/><section>{["USERS","ORDERS","PAYMENTS"].map((service)=><i key={service}>{service}</i>)}</section></div></div></section><nav className="chapter-nav" aria-label="Chapter sections"><div className="page-shell"><span>CHAPTER 07</span><div>{toc.map(([n,l,h])=><a href={h} key={n}><small>{n}</small>{l}</a>)}</div></div></nav>
<section className="lesson-section page-shell" id="entry"><Reveal><SectionHeading eyebrow="01 · THE CONFUSION" title="Same position. Different primary responsibility." copy="Architecture labels overlap. Start with the decision being made, then decide whether one product can safely own several responsibilities."/></Reveal><div className="edge-responsibilities"><div><span>LOAD BALANCER</span><h3>Choose an instance.</h3><p>Which healthy target should receive this connection or request?</p></div><div><span>REVERSE PROXY</span><h3>Represent origins.</h3><p>How should inbound traffic be handled and forwarded before servers?</p></div><div><span>API GATEWAY</span><h3>Govern APIs.</h3><p>Which policy and service should this API request pass through?</p></div></div></section>
<section className="lesson-section lesson-section--wide" id="proxy"><div className="page-shell"><Reveal><SectionHeading eyebrow="02 · REVERSE THE VIEW" title="Ask who the proxy represents." copy="A forward proxy stands in for clients. A reverse proxy stands in for servers and hides the origin topology behind one public endpoint."/></Reveal><Reveal delay={0.08}><ProxyPerspective/></Reveal></div></section>
<section className="lesson-section page-shell" id="gateway"><Reveal><SectionHeading eyebrow="03 · PLAY WITH THE PIPELINE" title="A gateway is a sequence of gates." copy="Change the request condition and see exactly where authentication, rate limiting, routing, or backend availability stops progress."/></Reveal><Reveal delay={0.08}><GatewayPipelineLab/></Reveal><div className="gateway-capabilities"><div><b>Routing</b><p>Map public paths to service ownership.</p></div><div><b>Authentication</b><p>Establish caller identity before forwarding.</p></div><div><b>Rate limits</b><p>Bound demand before it consumes service capacity.</p></div><div><b>Aggregation</b><p>Optionally combine service responses for a client-specific API.</p></div></div></section>
<section className="lesson-section lesson-section--wide" id="compare"><div className="page-shell"><Reveal><SectionHeading eyebrow="04 · COMPARE WITHOUT ABSOLUTES" title="Responsibilities overlap. Mental models still matter." copy="Use the primary question to reason clearly without claiming a reverse proxy can never balance traffic or a gateway can never proxy it."/></Reveal><Reveal delay={0.08}><EdgeRoleComparison/></Reveal><div className="break-edge"><span>BREAK THE EDGE</span><div><b>Missing reverse proxy</b><p>Clients reach an origin directly; origin addresses and edge-wide handling are no longer centralized.</p></div><div><b>Giant gateway</b><p>Too much custom business logic can turn the front door into a bottleneck and release-coupling point.</p></div><div><b>Unavailable backend</b><p>Bound timeouts and clear failures are safer than waiting or retrying forever.</p></div></div></div></section>
<section className="lesson-section page-shell" id="challenge"><Reveal><SectionHeading eyebrow="05 · APPLY IT" title="Guard the backend." copy="Safely route legitimate requests while rejecting invalid identity, missing permission, excessive traffic, and unknown routes."/></Reveal><Reveal delay={0.08}><GuardBackendGame/></Reveal></section>
<section className="takeaway-section"><div className="page-shell"><Reveal><SectionHeading eyebrow="EDGE LAYER SUMMARY" title="Balance instances. Represent origins. Govern APIs."/></Reveal><div className="topic-summary-grid"><div><span>01</span><b>Load balancer</b><p>Selects among healthy targets.</p></div><div><span>02</span><b>Reverse proxy</b><p>Acts on behalf of origin servers.</p></div><div><span>03</span><b>API gateway</b><p>Applies API-aware policy and routing.</p></div><div><span>04</span><b>Reality</b><p>One product may perform several roles.</p></div></div><div className="source-note"><span>SOURCE MAPPING</span><p>Derived from <a href="https://github.com/ChetanAmritanshu/High-Level-Design/blob/main/07_Reverse_Proxy_and_API_Gateway.docx" target="_blank" rel="noreferrer"><code>07_Reverse_Proxy_and_API_Gateway.docx</code></a>. The source establishes reverse proxy perspective, routing, authentication, rate limiting, aggregation, cross-cutting concerns, and gateway bottleneck risk.</p></div><LessonPager previous={{number:"06",title:"Load Balancers",href:"/learn/load-balancers"}} next={{number:"08",title:"Caching Fundamentals",href:"/learn/caching",copy:"Why repeat expensive work when a safe answer can be reused?"}}/><Link className="back-to-map" href="/#learning-map"><ServerIcon/> Return to the learning map <ArrowRight/></Link></div></section></article>}
