import type { Metadata } from "next";
import Link from "next/link";
import { ArrowDown, ArrowRight, ServerIcon } from "@/components/ui/icons";
import { ConceptChain } from "@/components/lesson/concept-chain";
import { LessonPager } from "@/components/lesson/lesson-pager";
import { HealthAndSessionLab, KeepFleetAliveGame, LoadBalancerLab } from "@/components/labs/load-balancer-labs";
import { Reveal } from "@/components/ui/reveal";
import { SectionHeading } from "@/components/ui/section-heading";

export const metadata: Metadata = { title:"Load Balancers", description:"Route traffic across a healthy server fleet and explore algorithms, health checks, and session state." };
const toc=[["01","One server","#pressure"],["02","Algorithms","#algorithms"],["03","Health + state","#health"],["04","Break it","#break"],["05","Challenge","#challenge"]] as const;
export default function LoadBalancersPage(){return <article className="lesson-page load-balancer-page"><section className="fleet-hero page-shell"><div className="lesson-breadcrumb"><Link href="/#learning-map">Learning map</Link><span>/</span><b>Networking</b><span>/</span><span>Chapter 06</span></div><ConceptChain current="06"/><div className="topic-hero-grid"><div><p className="eyebrow"><span/>TRAFFIC DISTRIBUTION · 26 MIN LAB</p><h1>One address.<br/><em>A fleet behind it.</em></h1><p className="lesson-deck">Adding servers creates capacity. A load balancer turns that capacity into one reachable, health-aware service.</p><a className="text-link" href="#pressure">Release the traffic <ArrowDown/></a></div><div className="fleet-hero-card"><div><small>10,000 CLIENTS</small><i/><b>LOAD BALANCER</b></div><span><i/><i/><i/></span><section>{["A","B","C"].map((name,index)=><div key={name}><ServerIcon/><small>SERVER {name}</small><b>{[42,67,31][index]}% LOAD</b><i><em style={{width:`${[42,67,31][index]}%`}}/></i></div>)}</section></div></div></section><nav className="chapter-nav" aria-label="Chapter sections"><div className="page-shell"><span>CHAPTER 06</span><div>{toc.map(([n,l,h])=><a href={h} key={n}><small>{n}</small>{l}</a>)}</div></div></nav>
<section className="lesson-section page-shell" id="pressure"><Reveal><SectionHeading eyebrow="01 · THE PRESSURE" title="More servers are useless without a traffic decision." copy="Clients need one stable entry point. That entry layer chooses a healthy target and stops one machine from receiving every request."/></Reveal><div className="single-server-pressure"><div><small>WITHOUT A BALANCER</small><h3>10,000 clients → Server A</h3><i><span/></i><b>CPU 100% · QUEUE GROWING</b></div><ArrowRight/><div><small>WITH A BALANCER</small><h3>Requests → A / B / C</h3><i><span/></i><b>CAPACITY SHARED</b></div></div><div className="layer-note"><span>L4</span><p>Routes using transport information such as IP addresses and ports.</p><span>L7</span><p>Can inspect application information such as HTTP host, path, or headers. Real products may combine layers.</p></div></section>
<section className="lesson-section lesson-section--wide" id="algorithms"><div className="page-shell"><Reveal><SectionHeading eyebrow="02 · PLAY WITH IT" title="The algorithm decides what “fair” means." copy="Send requests with equal rotation, active-load awareness, or capacity weights. Then watch the fleet react."/></Reveal><Reveal delay={0.08}><LoadBalancerLab/></Reveal></div></section>
<section className="lesson-section page-shell" id="health"><Reveal><SectionHeading eyebrow="03 · HEALTH + STATE" title="A target can disappear. User state cannot." copy="Health checks protect routing. Session design determines whether any healthy instance can continue a user's work."/></Reveal><Reveal delay={0.08}><HealthAndSessionLab/></Reveal></section>
<section className="lesson-section lesson-section--wide" id="break"><div className="page-shell"><Reveal><SectionHeading eyebrow="04 · BREAK THE FLEET" title="The balancer is infrastructure—and infrastructure can fail." copy="Removing a dead server protects requests, but a naive algorithm can still create a hot target, and a single load-balancer instance can become its own single point of failure."/></Reveal><div className="lb-failure-grid"><div><span>SERVER FAILURE</span><h3>Health checks remove the target.</h3><p>Detection is not instantaneous; in-flight requests may fail before the pool converges.</p></div><div><span>HOT SERVER</span><h3>An algorithm can be blind.</h3><p>Round robin treats targets equally even when request duration or hardware differs.</p></div><div><span>LB FAILURE</span><h3>The entry layer needs redundancy.</h3><p>Production designs run redundant balancers or managed control/data planes instead of one irreplaceable box.</p></div></div></div></section>
<section className="lesson-section page-shell" id="challenge"><Reveal><SectionHeading eyebrow="05 · APPLY IT" title="Keep the fleet alive." copy="Stabilize each traffic wave with the algorithm, health signal, or state strategy that fits the evidence."/></Reveal><Reveal delay={0.08}><KeepFleetAliveGame/></Reveal></section>
<section className="takeaway-section"><div className="page-shell"><Reveal><SectionHeading eyebrow="LOAD BALANCING SUMMARY" title="Distribute. Observe. Remove. Recover."/></Reveal><div className="topic-summary-grid"><div><span>01</span><b>Round robin</b><p>Simple rotation for similar healthy targets.</p></div><div><span>02</span><b>Least connections</b><p>Adapts to uneven request duration.</p></div><div><span>03</span><b>Weights</b><p>Express unequal capacity.</p></div><div><span>04</span><b>Health + state</b><p>Remove failures and decouple sessions.</p></div></div><div className="source-note"><span>SOURCE MAPPING</span><p>Derived from <a href="https://github.com/ChetanAmritanshu/High-Level-Design/blob/main/06_Load_Balancers.docx" target="_blank" rel="noreferrer"><code>06_Load_Balancers.docx</code></a>. The source maps L4/L7 balancing, round robin, least connections, sticky sessions, health checks, and failure behavior.</p></div><LessonPager previous={{number:"05",title:"Realtime Communication",href:"/learn/realtime-communication"}} next={{number:"07",title:"Reverse Proxy & API Gateway",href:"/learn/reverse-proxy-api-gateway",copy:"How should the public edge forward and govern requests?"}}/><Link className="back-to-map" href="/#learning-map"><ServerIcon/> Return to the learning map <ArrowRight/></Link></div></section></article>}
