import type { Metadata } from "next";
import Link from "next/link";
import { ArrowDown, ArrowRight, DatabaseIcon, ServerIcon } from "@/components/ui/icons";
import { ConceptChain } from "@/components/lesson/concept-chain";
import { LessonPager } from "@/components/lesson/lesson-pager";
import { CacheFailureLab, CacheRaceDemo, StopMeltdownGame, TTLTradeoffLab } from "@/components/labs/cache-failure-labs";
import { Reveal } from "@/components/ui/reveal";
import { SectionHeading } from "@/components/ui/section-heading";

export const metadata:Metadata={title:"Cache Invalidation & Failures",description:"See cache races, stampedes, penetration, avalanches, hot keys, and outage cascades."};
const toc=[["01","Wrong copy","#wrong"],["02","Race","#race"],["03","Incidents","#incidents"],["04","Challenge","#challenge"]] as const;
export default function CacheFailuresPage(){return <article className="lesson-page cache-failure-page"><section className="cache-failure-hero page-shell"><div className="lesson-breadcrumb"><Link href="/#learning-map">Learning map</Link><span>/</span><b>Performance</b><span>/</span><span>Chapter 10</span></div><ConceptChain current="10"/><div className="topic-hero-grid"><div><p className="eyebrow"><span/>INCIDENT SIMULATOR · 32 MIN LAB</p><h1>Fast can be<br/><em>confidently wrong.</em></h1><p className="lesson-deck">The hard part is not storing a copy. It is deciding when that copy stopped being true—and surviving the traffic when it disappears.</p><a className="text-link" href="#wrong">Open the incident <ArrowDown/></a></div><div className="stale-hero"><div><small>DATABASE · SOURCE</small><DatabaseIcon/><b>product:42 = ₹799</b></div><span>≠</span><div><small>CACHE · COPY</small><ServerIcon/><b>product:42 = ₹999</b></div><strong>USER SEES ₹999</strong></div></div></section><nav className="chapter-nav" aria-label="Chapter sections"><div className="page-shell"><span>CHAPTER 10</span><div>{toc.map(([n,l,h])=><a href={h} key={n}><small>{n}</small>{l}</a>)}</div></div></nav>
<section className="lesson-section page-shell" id="wrong"><Reveal><SectionHeading eyebrow="01 · INVALIDATION" title="Every freshness policy chooses a window." copy="TTL expiry bounds reuse. Explicit delete removes a known copy. Updating on write narrows the gap but introduces ordering. Versioned keys make old and new data distinct. Events can notify many cache owners but still arrive late or twice."/></Reveal><div className="invalidation-grid"><div><b>TTL</b><p>Simple bound; stale until expiry.</p></div><div><b>DELETE ON WRITE</b><p>Next read reloads; races still matter.</p></div><div><b>UPDATE ON WRITE</b><p>Refresh immediately; coordinate failures.</p></div><div><b>VERSIONED KEY</b><p>New version creates a new identity.</p></div><div><b>EVICTION</b><p>Removes entries for capacity policy; it is not proof that remaining values are fresh.</p></div></div><Reveal delay={0.08}><TTLTradeoffLab/></Reveal></section>
<section className="lesson-section lesson-section--wide" id="race"><div className="page-shell"><Reveal><SectionHeading eyebrow="02 · ORDERING BUG" title="Reasonable operations can interleave into stale state." copy="Advance Client A and Client B through a cache-aside race. The invalidation succeeds—then the older reader repopulates the cache."/></Reveal><Reveal delay={0.08}><CacheRaceDemo/></Reveal></div></section>
<section className="lesson-section page-shell" id="incidents"><Reveal><SectionHeading eyebrow="03 · FAILURE LAB" title="Read the traffic shape before naming the fix." copy="Stampede, penetration, avalanche, hot-key pressure, and cache outage look different at the cache but can all overload downstream storage."/></Reveal><Reveal delay={0.08}><CacheFailureLab/></Reveal><div className="failure-glossary"><div><b>Stampede</b><p>Concurrent misses regenerate one hot value.</p></div><div><b>Penetration</b><p>Repeated missing keys bypass the cache.</p></div><div><b>Avalanche</b><p>Many entries expire in the same window.</p></div><div><b>Hot key</b><p>One key overloads one cache path.</p></div><div><b>Outage</b><p>Fallback traffic amplifies dependency failure.</p></div></div></section>
<section className="lesson-section lesson-section--wide" id="challenge"><div className="page-shell"><Reveal><SectionHeading eyebrow="04 · INCIDENT RESPONSE" title="Stop the cache meltdown." copy="Diagnose five incidents and apply the control that changes their request pattern or limits their blast radius."/></Reveal><Reveal delay={0.08}><StopMeltdownGame/></Reveal></div></section>
<section className="takeaway-section"><div className="page-shell"><Reveal><SectionHeading eyebrow="CACHE FAILURE SUMMARY" title="Protect truth. Shape refresh work."/></Reveal><div className="topic-summary-grid"><div><span>01</span><b>Freshness</b><p>No TTL is correct for every workload.</p></div><div><span>02</span><b>Ordering</b><p>Races can reintroduce stale values.</p></div><div><span>03</span><b>Traffic shape</b><p>Simultaneous misses create nonlinear load.</p></div><div><span>04</span><b>Containment</b><p>Fallback needs limits and degraded modes.</p></div></div><div className="source-note"><span>SOURCE MAPPING</span><p>Derived from <a href="https://github.com/ChetanAmritanshu/High-Level-Design/blob/main/10_Cache_Invalidation_and_Advanced_Cache_Failures.docx" target="_blank" rel="noreferrer"><code>10_Cache_Invalidation_and_Advanced_Cache_Failures.docx</code></a>. The source establishes freshness-versus-performance, eviction, hot keys, stampedes, request coalescing, locks, jittered TTLs, and source-of-truth failure reasoning.</p></div><LessonPager previous={{number:"09",title:"Cache Architectures & Redis",href:"/learn/cache-architectures-redis"}} next={{number:"11",title:"CDNs & Edge Delivery",href:"/learn/cdn-edge-delivery",copy:"Move reusable content from a central cache to edges near users."}}/><Link className="back-to-map" href="/#learning-map"><ServerIcon/> Return to the learning map <ArrowRight/></Link></div></section></article>}
