import type { Metadata } from "next";
import Link from "next/link";
import { ArrowDown, ArrowRight, ServerIcon } from "@/components/ui/icons";
import { ConceptChain } from "@/components/lesson/concept-chain";
import { LessonPager } from "@/components/lesson/lesson-pager";
import { BreakRealtime, KeepChatLiveGame, RealtimeTransportLab } from "@/components/labs/realtime-labs";
import { Reveal } from "@/components/ui/reveal";
import { SectionHeading } from "@/components/ui/section-heading";

export const metadata: Metadata = { title:"Realtime Communication", description:"Compare polling, long polling, Server-Sent Events, and WebSockets through live local simulations." };
const toc = [["01","The delay","#delay"],["02","Compare","#compare"],["03","Channels","#channels"],["04","Break it","#break"],["05","Challenge","#challenge"]] as const;

export default function RealtimeCommunicationPage() { return <article className="lesson-page realtime-page">
  <section className="realtime-hero page-shell"><div className="lesson-breadcrumb"><Link href="/#learning-map">Learning map</Link><span>/</span><b>Networking</b><span>/</span><span>Chapter 05</span></div><ConceptChain current="05" /><div className="topic-hero-grid"><div><p className="eyebrow"><span />LIVE CHANNELS · 24 MIN LAB</p><h1>Stop asking.<br /><em>Start listening.</em></h1><p className="lesson-deck">HTTP works beautifully when the client asks. Realtime design begins when the server has news before the next request arrives.</p><a className="text-link" href="#delay">Watch the delay <ArrowDown /></a></div><div className="polling-hero-card"><div><small>CLIENT</small><b>Anything new?</b><ArrowRight /><span>SERVER · No.</span></div><i>2 seconds later…</i><div><small>CLIENT</small><b>Anything new?</b><ArrowRight /><span>SERVER · No.</span></div><strong>MESSAGE ARRIVES +100 ms<small>Client waits for the next poll.</small></strong></div></div></section>
  <nav className="chapter-nav" aria-label="Chapter sections"><div className="page-shell"><span>CHAPTER 05</span><div>{toc.map(([n,l,h])=><a href={h} key={n}><small>{n}</small>{l}</a>)}</div></div></nav>
  <section className="lesson-section page-shell" id="delay"><Reveal><SectionHeading eyebrow="01 · THE PROBLEM" title="Freshness has a clock." copy="A 10-second polling interval can show data almost 10 seconds late. A 500 ms interval feels live, but every quiet client still asks twice each second." /></Reveal><div className="realtime-problem-grid"><div><span>SHORT POLLING</span><h3>Ask, close, wait, repeat.</h3><p>Simple HTTP. Detection delay follows the interval; idle requests spend server work proving nothing changed.</p></div><div><span>LONG POLLING</span><h3>Ask once, let the server wait.</h3><p>The server holds the response until an event or timeout. After responding, the client reconnects.</p></div></div></section>
  <section className="lesson-section lesson-section--wide" id="compare"><div className="page-shell"><Reveal><SectionHeading eyebrow="02 · PLAY WITH IT" title="Choose a connection lifecycle." copy="Switch transports and watch request count, directionality, delay, and open-connection behavior change for the same stream of events." /></Reveal><Reveal delay={0.08}><RealtimeTransportLab /></Reveal></div></section>
  <section className="lesson-section page-shell" id="channels"><Reveal><SectionHeading eyebrow="03 · NEW CONCEPT" title="A stream is not automatically a conversation." copy="SSE and WebSockets both keep connections open, but they solve different directionality and state-management problems." /></Reveal><div className="channel-models"><div><span>SSE</span><h3>Server → client event stream</h3><p>A long-lived HTTP response carries named text events. Browsers can reconnect; client commands still use requests.</p><code>event: price{`\n`}data: 104.20</code></div><div><span>WEBSOCKET</span><h3>Client ↔ server messages</h3><p>After the opening handshake, either side sends frames independently. Reconnect and missed-event recovery are application concerns.</p><code>client ⇄ persistent channel ⇄ server</code></div></div></section>
  <section className="lesson-section lesson-section--wide" id="break"><div className="page-shell"><Reveal><SectionHeading eyebrow="04 · BREAK IT" title="Every realtime choice can fail differently." copy="Increase delay, flood the server with empty polls, disconnect a socket, or force a one-way stream into a two-way workload." /></Reveal><Reveal delay={0.08}><BreakRealtime /></Reveal></div></section>
  <section className="lesson-section page-shell" id="challenge"><Reveal><SectionHeading eyebrow="05 · APPLY IT" title="Keep the chat live." copy="Choose from workload shape—not fashion. Some products need WebSockets; some need a one-way stream; some only need a humble timer." /></Reveal><Reveal delay={0.08}><KeepChatLiveGame /></Reveal></section>
  <section className="takeaway-section"><div className="page-shell"><Reveal><SectionHeading eyebrow="REALTIME SUMMARY" title="Match direction, delay, and lifecycle." /></Reveal><div className="topic-summary-grid"><div><span>01</span><b>Polling</b><p>Repeated requests trade simplicity for delay and idle traffic.</p></div><div><span>02</span><b>Long polling</b><p>Hold a request, respond on change, then reconnect.</p></div><div><span>03</span><b>SSE</b><p>One-way server events over a long-lived HTTP response.</p></div><div><span>04</span><b>WebSocket</b><p>Persistent full-duplex messaging with connection-state costs.</p></div></div><div className="source-note"><span>SOURCE MAPPING</span><p>Derived from <a href="https://github.com/ChetanAmritanshu/High-Level-Design/blob/main/05_Realtime_Communication_Polling_SSE_and_WebSockets.docx" target="_blank" rel="noreferrer"><code>05_Realtime_Communication_Polling_SSE_and_WebSockets.docx</code></a>. The source emphasizes polling, long polling, SSE, WebSockets, directionality, lifecycle, and scaling persistent connections.</p></div><LessonPager previous={{number:"04",title:"HTTP Evolution",href:"/learn/http-evolution"}} next={{number:"06",title:"Load Balancers",href:"/learn/load-balancers",copy:"How do many healthy servers share one growing traffic stream?"}} /><Link className="back-to-map" href="/#learning-map"><ServerIcon /> Return to the learning map <ArrowRight /></Link></div></section>
  </article>; }
