import type { Metadata } from "next";
import Link from "next/link";
import { ArrowDown, ArrowRight, ServerIcon } from "@/components/ui/icons";
import { ConceptChain } from "@/components/lesson/concept-chain";
import { LessonPager } from "@/components/lesson/lesson-pager";
import { CDNInvalidationLab, CDNRequestLab, ServeWorldGame } from "@/components/labs/cdn-labs";
import { Reveal } from "@/components/ui/reveal";
import { SectionHeading } from "@/components/ui/section-heading";

export const metadata:Metadata={title:"CDNs & Edge Delivery",description:"Explore edge hits, origin misses, cache keys, invalidation, and global content delivery."};
const toc=[["01","Distance","#distance"],["02","Edge lab","#edge"],["03","Correctness","#correctness"],["04","Challenge","#challenge"]] as const;
export default function CDNPage(){return <article className="lesson-page cdn-page"><section className="cdn-hero page-shell"><div className="lesson-breadcrumb"><Link href="/#learning-map">Learning map</Link><span>/</span><b>Performance</b><span>/</span><span>Chapter 11</span></div><ConceptChain current="11"/><div className="topic-hero-grid"><div><p className="eyebrow"><span/>GLOBAL DELIVERY · 28 MIN LAB</p><h1>Move bytes<br/><em>closer to people.</em></h1><p className="lesson-deck">Why make every user cross an ocean to reach one origin when reusable content can wait at a nearby edge?</p><a className="text-link" href="#distance">Cross the network <ArrowDown/></a></div><div className="world-hero"><div className="world-origin"><small>ORIGIN</small><b>VIRGINIA</b></div><i/><div className="world-edge"><small>EDGE PoP</small><b>MUMBAI</b></div><i/><div className="world-user"><small>USER</small><b>MUMBAI</b></div><span>Origin path ~200 ms · edge hit ~22 ms</span></div></div></section><nav className="chapter-nav" aria-label="Chapter sections"><div className="page-shell"><span>CHAPTER 11</span><div>{toc.map(([n,l,h])=><a href={h} key={n}><small>{n}</small>{l}</a>)}</div></div></nav>
<section className="lesson-section page-shell" id="distance"><Reveal><SectionHeading eyebrow="01 · GEOGRAPHY IS LATENCY" title="The origin owns content. Edges deliver nearby copies." copy="A CDN routes users toward points of presence. On a hit, the edge responds. On a miss, it fetches from the origin, stores according to HTTP policy, and serves the user."/></Reveal><div className="edge-network"><div><b>ORIGIN</b><small>authoritative content</small></div>{["LONDON","MUMBAI","SINGAPORE"].map(city=><div key={city}><span>EDGE</span><b>{city}</b><small>nearby users</small></div>)}</div><p className="illustrative-note">Latency values throughout this lesson are deterministic teaching examples, not measurements.</p></section>
<section className="lesson-section lesson-section--wide" id="edge"><div className="page-shell"><Reveal><SectionHeading eyebrow="02 · EDGE HIT / MISS" title="The first request travels farther." copy="Choose an asset, request it twice, then fail the edge or origin. Notice that cacheability is a policy—not a file-type law."/></Reveal><Reveal delay={0.08}><CDNRequestLab/></Reveal></div></section>
<section className="lesson-section page-shell" id="correctness"><Reveal><SectionHeading eyebrow="03 · CACHE KEY & INVALIDATION" title="A nearby wrong response is still wrong." copy="Query parameters, headers, cookies, authorization, and policy can affect the cache key. Sharing a personalized response under a path-only key is a privacy and correctness failure."/></Reveal><div className="cache-key-grid"><div><code>/products?id=42</code><b>PUBLIC PRODUCT 42</b></div><div><code>/products?id=43</code><b>DIFFERENT KEY</b></div><div className="danger"><code>/user/profile + Authorization</code><b>DO NOT SHARE BY PATH ALONE</b></div></div><Reveal delay={0.08}><CDNInvalidationLab/></Reveal><div className="cdn-not-redis"><b>A CDN is not “Redis farther away.”</b><p>It combines geographically distributed PoPs, request routing, HTTP caching semantics, origin protection, and delivery over the network. Modern CDNs can accelerate dynamic traffic too; cacheability depends on policy.</p></div></section>
<section className="lesson-section lesson-section--wide" id="challenge"><div className="page-shell"><Reveal><SectionHeading eyebrow="04 · APPLY IT" title="Serve the world." copy="Select origin, edge, TTL, invalidation, and bypass behavior for global public assets and personalized responses."/></Reveal><Reveal delay={0.08}><ServeWorldGame/></Reveal></div></section>
<section className="takeaway-section"><div className="page-shell"><Reveal><SectionHeading eyebrow="EDGE DELIVERY SUMMARY" title="Distance, identity, and freshness shape delivery."/></Reveal><div className="topic-summary-grid"><div><span>01</span><b>PoP</b><p>A nearby edge shortens the delivery path.</p></div><div><span>02</span><b>Hit / miss</b><p>Misses fetch origin; hits reuse the edge copy.</p></div><div><span>03</span><b>Cache key</b><p>Response identity must include meaningful variation.</p></div><div><span>04</span><b>Invalidation</b><p>TTL, purge, or versioning replaces old content.</p></div></div><div className="source-note"><span>SOURCE MAPPING</span><p>Derived from <a href="https://github.com/ChetanAmritanshu/High-Level-Design/blob/main/11_CDNs_and_Edge_Delivery.docx" target="_blank" rel="noreferrer"><code>11_CDNs_and_Edge_Delivery.docx</code></a>. The source establishes origin-versus-edge delivery, geographic distribution, cacheability, static and immutable content, invalidation, viral traffic, and failure trade-offs.</p></div><LessonPager previous={{number:"10",title:"Cache Invalidation & Advanced Failures",href:"/learn/cache-invalidation-failures"}} next={{number:"12",title:"Rate Limiting",copy:"Protecting services from excessive demand is coming next."}}/><Link className="back-to-map" href="/#learning-map"><ServerIcon/> Return to the learning map <ArrowRight/></Link></div></section></article>}
