"use client";

import { useState } from "react";
import { ArrowRight, DatabaseIcon, Rotate, SparkIcon } from "@/components/ui/icons";
import { MiniGameShell } from "@/components/ui/mini-game-shell";

type KeyName = "product:42"|"product:17"|"user:10";
const origin: Record<KeyName,string> = { "product:42":"₹999", "product:17":"₹349", "user:10":"Alice" };

export function CacheLab() {
  const [cache,setCache] = useState<Partial<Record<KeyName,{value:string;ttl:number}>>>({}); const [last,setLast] = useState<{key:KeyName;hit:boolean;latency:number}|null>(null); const [now,setNow] = useState(0);
  const request = (key:KeyName) => { const entry=cache[key]; const hit=Boolean(entry && entry.ttl>now); if (!hit) setCache((value)=>({...value,[key]:{value:origin[key],ttl:now+30}})); setLast({key,hit,latency:hit?4:180}); };
  const advance = () => setNow((value)=>value+10);
  return <div className="cache-lab lab-panel"><div className="lab-toolbar"><div><span className="live-dot" /> CACHE HIT / MISS LAB <b>01</b></div><span>SIMULATED CLOCK · {now}s</span></div><div className="cache-request-buttons">{(Object.keys(origin) as KeyName[]).map((key)=><button type="button" onClick={()=>request(key)} key={key}>GET <b>{key}</b></button>)}</div><div className="cache-path"><div><small>APPLICATION</small><b>REQUEST KEY</b></div><ArrowRight /><div className={last?.hit?"cache-node cache-node--hit":"cache-node"}><SparkIcon /><small>CACHE</small><b>{last ? last.hit ? "HIT · RETURN" : "MISS · FILL" : "WAITING"}</b></div><ArrowRight /><div className={last && !last.hit?"origin-node origin-node--active":"origin-node"}><DatabaseIcon /><small>DATABASE</small><b>{last && !last.hit ? "180 ms LOOKUP" : "SOURCE OF TRUTH"}</b></div></div><div className="cache-slots">{(Object.keys(origin) as KeyName[]).map((key)=>{const entry=cache[key]; const remaining=entry?Math.max(0,entry.ttl-now):0; return <div className={remaining?"filled":""} key={key}><small>{key}</small><b>{remaining?entry?.value:"EMPTY"}</b><span>TTL {remaining}s</span><i><em style={{width:`${remaining/30*100}%`}} /></i></div>;})}</div><div className="cache-result"><span><small>LAST RESULT</small><b>{last?`${last.hit?"HIT":"MISS"} · ${last.latency} ms`:"REQUEST A KEY"}</b></span><button type="button" className="lab-button" onClick={advance}>+10s ADVANCE TIME</button><button type="button" className="quiet-button" onClick={()=>{setCache({});setLast(null);setNow(0);}}><Rotate />COLD CACHE</button></div><div className="observation"><span>{last?.hit?"FAST PATH":last?"NORMAL MISS PATH":"LOCALITY BUILDS VALUE"}</span><p>{last?.hit?"The application reused a still-valid copy and avoided the database.":last?"A miss fetched authoritative data, filled the cache, and returned the result. The next identical request can hit.":"Repeated access creates temporal locality. Cache usefulness depends on which keys repeat and how fresh they must be."} Timings are illustrative.</p></div></div>;
}

type Pattern = "hot"|"skewed"|"random";
const patternData = { hot:{hits:92,copy:"One product dominates requests, so a small cache captures most reads."}, skewed:{hits:78,copy:"A small hot set repeats often enough to produce a strong hit ratio."}, random:{hits:18,copy:"Low locality means most keys are seen once; cache space buys much less."} } as const;
export function HitRatioLab() { const [pattern,setPattern]=useState<Pattern>("skewed"); const item=patternData[pattern]; return <div className="hit-ratio lab-panel"><div className="lab-toolbar"><div><span className="live-dot" /> HIT RATIO <b>02</b></div><span>100 REQUESTS</span></div><div className="ratio-tabs" role="tablist">{(["hot","skewed","random"] as Pattern[]).map((id)=><button type="button" role="tab" aria-selected={pattern===id} onClick={()=>setPattern(id)} key={id}>{id === "hot"?"REPEATED HOT KEY":id === "skewed"?"SKEWED HOT SET":"RANDOM KEYS"}</button>)}</div><div className="ratio-display"><div><small>HITS</small><b>{item.hits}</b><i><span style={{width:`${item.hits}%`}} /></i></div><div><small>MISSES</small><b>{100-item.hits}</b><i><span style={{width:`${100-item.hits}%`}} /></i></div><strong>{item.hits}%<small>HIT RATIO</small></strong></div><div className="observation"><span>WORKLOAD LOCALITY</span><p>{item.copy} Hit ratio is hits ÷ total lookups; it is not a property of the cache alone.</p></div></div>; }

type Failure = "miss"|"expired"|"stale"|"outage"|"cold";
const failureData: Record<Failure,[string,string,string]> = {
  miss:["CACHE MISS","1 DB query","The key is absent. Fetching from the database and filling the cache is normal behavior."],
  expired:["TTL EXPIRED","Fresh value loaded","An expired entry is treated as a miss so the application can fetch current data."],
  stale:["STALE VALUE","Cache ₹999 · DB ₹899","The source changed before TTL expiry. Longer TTL improves hits but increases this freshness window."],
  outage:["CACHE OUTAGE","100% DB traffic","The application can fall back to the database, but downstream pressure jumps abruptly."],
  cold:["COLD CACHE","First wave all misses","A restart or empty cache initially provides no protection. Warm-up behavior matters under load."],
};
export function BreakCache() { const [failure,setFailure]=useState<Failure>("miss"); const item=failureData[failure]; return <div className={`break-cache break-cache--${failure} lab-panel`}><div className="lab-toolbar"><div><span className="alert-dot" /> BREAK THE CACHE <b>03</b></div><span>DOWNSTREAM PRESSURE</span></div><div className="cache-failure-stage"><div><small>10,000 REQUESTS</small><b>APPLICATION</b></div><span><i style={{width:failure==="outage"||failure==="cold"?"100%":failure==="stale"?"12%":"35%"}} /><strong>{item[1]}</strong></span><div><DatabaseIcon /><small>DATABASE</small><b>{failure==="outage"||failure==="cold"?"DANGER · 100%":"ABSORBING MISSES"}</b></div></div><div className="failure-buttons">{(Object.keys(failureData) as Failure[]).map((id)=><button type="button" className={failure===id?"active":""} onClick={()=>setFailure(id)} key={id}>{id.toUpperCase()}</button>)}</div><div className="observation"><span>{item[0]}</span><p>{item[2]} Advanced stampede protection belongs in the next cache-failure lesson.</p></div></div>; }

const rounds = [
  { title:"Hot product page", traffic:"70% product:42 · 20% product:17 · 10% random", options:["Cache hot products · TTL 60s","Disable cache","Cache random IDs only"], answer:0, hit:88, stale:"LOW", why:"Strong locality makes hot product values valuable cache candidates; a moderate TTL removes most repeated database reads." },
  { title:"Rapid inventory", traffic:"Stock changes often · overselling is costly", options:["TTL 10 minutes","Short TTL + selective cache","Cache forever"], answer:1, hit:54, stale:"CONTROLLED", why:"A conservative TTL accepts more misses to narrow the stale-inventory window. Correctness may also require authoritative checks on purchase." },
  { title:"Database under load", traffic:"Repeated catalog reads dominate; writes are modest", options:["Cache catalog · TTL 2 minutes","Cache bank balances forever","No cache during peak"], answer:0, hit:91, stale:"BOUNDED", why:"Caching the read-heavy, reusable catalog sheds database load while a bounded TTL limits staleness." },
] as const;
export function SaveDatabaseGame() { const [round,setRound]=useState(0); const [choice,setChoice]=useState<number|null>(null); const complete=round>=rounds.length; const current=rounds[Math.min(round,rounds.length-1)]; const correct=choice===current.answer; const dbLoad=choice===null?100:correct?100-current.hit:82; return <MiniGameShell title="SAVE THE DATABASE" round={round} total={rounds.length} feedback={choice===null?undefined:correct?current.why:`That setting misses the locality or freshness requirement. ${current.why}`} feedbackTone={choice===null?"neutral":correct?"success":"error"} feedbackSuccessLabel="DATABASE PROTECTED ✓" feedbackErrorLabel="TRADE-OFF MISSED" complete={complete} completeTitle="CACHE TRADE-OFFS UNDERSTOOD" completeCopy="You balanced hit ratio, backend load, TTL, and stale-data risk instead of caching every value indefinitely." onRestart={()=>{setRound(0);setChoice(null);}}><div className="cache-game-scenario"><small>TRAFFIC MODEL {String(round+1).padStart(2,"0")}</small><h3>{current.title}</h3><p>{current.traffic}</p><div><span><small>DATABASE LOAD</small><i><b style={{width:`${dbLoad}%`}} /></i><em>{dbLoad}%</em></span><span><small>HIT RATIO</small><b>{choice===null?"—":correct?`${current.hit}%`:"18%"}</b></span><span><small>STALE RISK</small><b>{choice===null?"—":correct?current.stale:"HIGH"}</b></span></div></div><div className="game-choice-row">{current.options.map((option,index)=><button type="button" disabled={choice!==null} onClick={()=>setChoice(index)} key={option}>{option}</button>)}</div><div className="game-footer"><span />{choice!==null?correct?<button type="button" className="lab-button" onClick={()=>{setRound((value)=>value+1);setChoice(null);}}>{round===rounds.length-1?"FINISH":"NEXT TRAFFIC MODEL"}<ArrowRight /></button>:<button type="button" className="lab-button" onClick={()=>setChoice(null)}><Rotate />TRY AGAIN</button>:null}</div></MiniGameShell>; }
