"use client";

import { useState } from "react";
import { ArrowRight, Rotate } from "@/components/ui/icons";
import { MiniGameShell } from "@/components/ui/mini-game-shell";

export function TTLTradeoffLab(){const [ttl,setTtl]=useState(300);const pct=(Math.log10(ttl)-0)/(Math.log10(3600))*100;const label=ttl<30?"VERY FRESH":ttl<300?"FRESH":ttl<1200?"BALANCED":"STALE WINDOW GROWS";return <div className="ttl-tradeoff lab-panel"><div className="lab-toolbar"><div><span className="live-dot"/> TTL TRADE-OFF LAB <b>01</b></div><span>{ttl<60?`${ttl}s`:`${Math.round(ttl/60)} min`}</span></div><div className="ttl-control"><label htmlFor="ttl">TTL</label><input id="ttl" type="range" min="0" max="100" value={pct} onChange={e=>setTtl(Math.max(1,Math.round(10**(Number(e.target.value)/100*Math.log10(3600)))))} aria-valuetext={`${ttl} seconds`}/><div><span>1 SEC</span><span>1 HOUR</span></div></div><div className="ttl-signals"><span><small>CACHE HIT TENDENCY</small><i><b style={{width:`${25+pct*.7}%`}}/></i><em>{pct<35?"LOW":pct<70?"MEDIUM":"HIGH"}</em></span><span><small>BACKEND LOAD</small><i><b style={{width:`${90-pct*.7}%`}}/></i><em>{pct<35?"HIGH":pct<70?"MEDIUM":"LOW"}</em></span><span><small>STALE-DATA WINDOW</small><i><b style={{width:`${10+pct*.85}%`}}/></i><em>{label}</em></span></div><div className="observation"><span>NO MAGIC TTL</span><p>Longer reuse usually improves hit tendency and reduces origin work, but permits an older copy to survive longer. These signals are qualitative, not production probabilities.</p></div></div>}

export function CacheRaceDemo(){const [step,setStep]=useState(0);const steps=["A reads DB value v1","B writes DB value v2","B invalidates cache","A fills cache with old v1","STALE CACHE"];return <div className="race-demo lab-panel"><div className="lab-toolbar"><div><span className={step===4?"alert-dot":"live-dot"}/> CACHE-ASIDE RACE <b>02</b></div><span>ORDERING MATTERS</span></div><div className="race-timeline">{steps.map((item,index)=><div className={index<step?"done":index===step?"active":""} key={item}><span>{index+1}</span><b>{item}</b></div>)}</div><div className="lab-actions"><button type="button" onClick={()=>setStep(v=>Math.min(4,v+1))} disabled={step===4}>NEXT EVENT</button><button type="button" onClick={()=>setStep(0)}><Rotate/>RESET</button></div><div className="observation"><span>{step===4?"STALE VALUE WON THE RACE":"INTERLEAVED OPERATIONS"}</span><p>{step===4?"Invalidation happened before the older read filled the cache. TTL, version checks, ordering, or write-side policies can bound or prevent this outcome.":"Advance the two clients. Each operation is reasonable alone; their ordering creates the bug."}</p></div></div>}

type Failure="stampede"|"penetration"|"avalanche"|"hot"|"outage";
const failures={stampede:{title:"HOT KEY EXPIRES",requests:1000,cache:"ALL MISS",db:100,impact:"Latency spike",mitigation:"single-flight",control:"ENABLE SINGLE-FLIGHT",after:18,copy:"One request regenerates while the rest wait for or share its result."},penetration:{title:"MISSING IDS REPEAT",requests:800,cache:"NEVER STORED",db:82,impact:"Wasteful lookups",mitigation:"negative cache",control:"NEGATIVE CACHE",after:15,copy:"Cache a bounded 'not found' result so repeated invalid keys stop reaching the database."},avalanche:{title:"10,000 KEYS EXPIRE",requests:10000,cache:"SAME TTL",db:100,impact:"Origin flood",mitigation:"TTL jitter",control:"ADD TTL JITTER",after:28,copy:"Spread expirations across a window instead of concentrating refresh work at one instant."},hot:{title:"ONE VIRAL KEY",requests:500000,cache:"ONE NODE HOT",db:38,impact:"Cache node saturated",mitigation:"local hot-key copy",control:"ADD LOCAL HOT CACHE",after:14,copy:"Replicate the exceptionally hot value closer to callers while keeping freshness bounded."},outage:{title:"REDIS UNAVAILABLE",requests:10000,cache:"BYPASSED",db:100,impact:"Cascade risk",mitigation:"fallback limits",control:"LIMIT FALLBACK",after:42,copy:"Circuit breaking, stale serving, and admission limits stop fallback traffic from destroying the database."}} as const;
export function CacheFailureLab(){const [mode,setMode]=useState<Failure>("stampede");const [mitigated,setMitigated]=useState(false);const item=failures[mode];return <div className={`failure-lab failure-lab--${mode} lab-panel`}><div className="lab-toolbar"><div><span className={mitigated?"live-dot":"alert-dot"}/> CACHE INCIDENT LAB <b>03</b></div><span>{mitigated?item.mitigation.toUpperCase():"INCIDENT ACTIVE"}</span></div><div className="failure-tabs" role="tablist">{(Object.keys(failures) as Failure[]).map(id=><button type="button" role="tab" aria-selected={mode===id} onClick={()=>{setMode(id);setMitigated(false);}} key={id}>{id.toUpperCase()}</button>)}</div><div className="failure-flood"><div><small>REQUEST PATTERN</small><b>{item.title}</b><em>{item.requests.toLocaleString()} requests</em></div><div className="flood-arrows">{Array.from({length:12},(_,i)=><i key={i} style={{animationDelay:`${i*50}ms`}}>↓</i>)}</div><div><small>CACHE</small><b>{mitigated?item.mitigation.toUpperCase():item.cache}</b></div><ArrowRight/><div className={(!mitigated&&item.db>70)?"danger":""}><small>DATABASE LOAD</small><strong>{mitigated?item.after:item.db}%</strong><i><b style={{width:`${mitigated?item.after:item.db}%`}}/></i></div></div><div className="lab-actions"><button type="button" className={mitigated?"active":""} onClick={()=>setMitigated(true)}>{item.control}</button><button type="button" onClick={()=>setMitigated(false)}><Rotate/>RESET INCIDENT</button></div><div className="observation"><span>{mitigated?"PRESSURE CONTAINED":item.impact.toUpperCase()}</span><p>{mitigated?item.copy:"Observe the request shape, cache behavior, and downstream impact before applying the targeted mitigation."}</p></div></div>}

const rounds=[
 {title:"Flash-sale key expires",options:["Single-flight regeneration","Retry every request","Identical TTLs"],answer:0,why:"Single-flight coalesces concurrent misses so one request regenerates the hot value."},
 {title:"Bots request nonexistent IDs",options:["Negative cache","Longer DB timeout","Write-back"],answer:0,why:"A short negative-cache entry prevents repeated known-missing keys from penetrating to storage."},
 {title:"All keys expire at noon",options:["TTL jitter","One global TTL","Disable cache"],answer:0,why:"Jitter distributes expirations and refresh work over time."},
 {title:"One viral profile dominates",options:["Local hot-key copies","Random retries","Shorten every TTL"],answer:0,why:"A bounded local/replicated copy can spread one key's extreme read pressure."},
 {title:"Redis cluster unavailable",options:["Unlimited DB fallback","Fallback limits + stale serving","Retry storm"],answer:1,why:"Controlled degradation protects the database and may serve bounded stale data where policy permits."},
] as const;
export function StopMeltdownGame(){const [round,setRound]=useState(0);const [choice,setChoice]=useState<number|null>(null);const complete=round>=rounds.length;const current=rounds[Math.min(round,rounds.length-1)];const correct=choice===current.answer;return <MiniGameShell title="STOP THE CACHE MELTDOWN" round={round} total={rounds.length} feedback={choice===null?undefined:correct?current.why:`That response does not match this incident's request pattern. ${current.why}`} feedbackTone={choice===null?"neutral":correct?"success":"error"} feedbackSuccessLabel="INCIDENT CONTAINED ✓" complete={complete} completeTitle="CACHE FAILURE MODES UNDERSTOOD" completeCopy="You diagnosed request shape before choosing a mitigation and protected the source of truth from cascading load." onRestart={()=>{setRound(0);setChoice(null);}}><div className="incident-scenario"><small>INCIDENT {round+1}</small><h3>{current.title}</h3><p>Choose the control that addresses the cause, not only the symptom.</p></div><div className="game-choice-row">{current.options.map((o,i)=><button type="button" disabled={choice!==null} onClick={()=>setChoice(i)} key={o}>{o}</button>)}</div><div className="game-footer"><span/>{choice!==null?correct?<button type="button" className="lab-button" onClick={()=>{setRound(v=>v+1);setChoice(null);}}>{round===rounds.length-1?"CLOSE INCIDENT":"NEXT INCIDENT"}<ArrowRight/></button>:<button type="button" className="lab-button" onClick={()=>setChoice(null)}><Rotate/>TRY AGAIN</button>:null}</div></MiniGameShell>}
