"use client";

import { useState } from "react";
import { ArrowRight, DatabaseIcon, Rotate, ServerIcon, SparkIcon } from "@/components/ui/icons";
import { MiniGameShell } from "@/components/ui/mini-game-shell";

type Pattern = "aside" | "through" | "write-through" | "write-back";
const patterns = {
  aside: { name: "CACHE ASIDE", read: ["APP", "CACHE", "MISS", "DATABASE", "FILL CACHE", "RETURN"], write: ["APP", "DATABASE", "INVALIDATE", "RETURN"], tendency: "Simple ownership · miss penalty · stale-copy risk", failure: "App can bypass cache, but database pressure rises." },
  through: { name: "READ THROUGH", read: ["APP", "CACHE PROVIDER", "MISS", "DATABASE", "FILL", "RETURN"], write: ["APP", "DATABASE", "INVALIDATE", "RETURN"], tendency: "Loading policy leaves the application", failure: "Provider failure can block the read path unless bypass exists." },
  "write-through": { name: "WRITE THROUGH", read: ["APP", "CACHE", "HIT", "RETURN"], write: ["APP", "CACHE", "DATABASE", "ACK"], tendency: "Fresh reads · slower writes · unused data may be cached", failure: "Write waits for the durable store; partial failure needs a policy." },
  "write-back": { name: "WRITE BACK", read: ["APP", "CACHE", "HIT", "RETURN"], write: ["APP", "CACHE", "FAST ACK", "LATER FLUSH"], tendency: "Fast writes · asynchronous durability risk", failure: "Crash before flush can lose acknowledged data." },
} as const;

export function CacheArchitectureLab() {
  const [pattern, setPattern] = useState<Pattern>("aside");
  const [action, setAction] = useState<"read" | "write" | "failure">("read");
  const item = patterns[pattern];
  const steps = action === "failure" ? pattern === "write-back" ? ["APP", "CACHE ACK", "CRASH", "UNFLUSHED WRITE LOST"] : ["APP", "CACHE DOWN", "FALLBACK", "DATABASE LOAD ↑"] : item[action];
  return <div className="architecture-lab lab-panel"><div className="lab-toolbar"><div><span className={action === "failure" ? "alert-dot" : "live-dot"}/> CACHE ARCHITECTURE LAB <b>01</b></div><span>{item.name}</span></div><div className="pattern-tabs" role="tablist">{(Object.keys(patterns) as Pattern[]).map(id=><button type="button" role="tab" aria-selected={pattern===id} onClick={()=>{setPattern(id);setAction("read");}} key={id}>{patterns[id].name}</button>)}</div><div className={`architecture-sequence architecture-sequence--${action}`}>{steps.map((step,index)=><div key={`${step}-${index}`} className={step.includes("CRASH")||step.includes("LOST")||step.includes("DOWN")?"danger":""}><span>{String(index+1).padStart(2,"0")}</span><b>{step}</b>{index<steps.length-1?<ArrowRight/>:null}</div>)}</div><div className="lab-actions"><button type="button" className={action==="read"?"active":""} onClick={()=>setAction("read")}>READ</button><button type="button" className={action==="write"?"active":""} onClick={()=>setAction("write")}>WRITE</button><button type="button" className={action==="failure"?"active danger":""} onClick={()=>setAction("failure")}>CACHE FAILURE</button></div><div className="architecture-metrics"><span><small>LATENCY / FRESHNESS TENDENCY</small><b>{item.tendency}</b></span><span><small>FAILURE IMPLICATION</small><b>{item.failure}</b></span></div></div>;
}

export function CachePlacementLab() {
  const [shared,setShared]=useState(false); const [version,setVersion]=useState(1); const [redisUp,setRedisUp]=useState(true);
  const update=()=>setVersion(v=>v+1);
  return <div className="placement-lab lab-panel"><div className="lab-toolbar"><div><span className={redisUp?"live-dot":"alert-dot"}/> LOCAL VS DISTRIBUTED <b>02</b></div><span>VALUE v{version}</span></div><div className="placement-toggle"><button type="button" aria-pressed={!shared} onClick={()=>{setShared(false);setRedisUp(true);}}>LOCAL CACHES</button><button type="button" aria-pressed={shared} onClick={()=>setShared(true)}>SHARED REDIS</button></div><div className={`app-fleet ${shared?"app-fleet--shared":""}`}>{["A","B","C"].map((app,index)=><div key={app}><ServerIcon/><b>APP {app}</b><span>{shared?"shared Redis":`Cache ${app}`}</span><em>{shared?redisUp?`v${version}`:"UNAVAILABLE":index===0?`v${version}`:`v${Math.max(1,version-1)}`}</em></div>)}<ArrowRight/><div className={`redis-node ${!redisUp?"redis-node--down":""}`}><SparkIcon/><b>{shared?"REDIS":"DATABASE"}</b><span>{shared?redisUp?`shared v${version}`:"OFFLINE":`source v${version}`}</span></div><ArrowRight/><div className="db-node"><DatabaseIcon/><b>DATABASE</b><span>authoritative v{version}</span></div></div><div className="lab-actions"><button type="button" onClick={update}>UPDATE DATA</button><button type="button" disabled={!shared} className={!redisUp?"danger":""} onClick={()=>setRedisUp(v=>!v)}>{redisUp?"KILL REDIS":"RECOVER REDIS"}</button><button type="button" onClick={()=>{setVersion(1);setRedisUp(true);}}><Rotate/> RESET</button></div><div className="observation"><span>{shared?redisUp?"ONE SHARED VIEW":"FAILURE AMPLIFIER":"COPIES CAN DISAGREE"}</span><p>{shared?redisUp?"All application instances see the same cache state, paying a network hop to avoid duplicated, divergent local copies.":"Fallback sends the fleet toward the database at once. Limits and degraded behavior protect the source of truth.":"Local memory is fastest, but an update on App A does not automatically refresh App B or C."}</p></div></div>;
}

const rounds=[
  {title:"Read-heavy product catalog", options:["Cache aside with bounded TTL","Write back every price","No shared cache"], answer:0, why:"Cache-aside loads only requested products and accepts a bounded freshness window."},
  {title:"Critical banking write", options:["Write back and acknowledge immediately","Write through to durable storage","Local cache only"], answer:1, why:"Durability matters more than the fastest acknowledgement; write-back risks loss before flush."},
  {title:"High-volume analytics counters", options:["Write back with loss budget","Synchronous DB read per event","Cache forever"], answer:0, why:"Delayed persistence can be reasonable when the product explicitly tolerates bounded loss and monitors flushes."},
  {title:"Sessions across an app fleet", options:["Separate local caches","Shared distributed cache","Browser memory only"], answer:1, why:"A shared cache lets any healthy instance resolve the same session, though Redis availability must be designed."},
] as const;
export function DesignCacheGame(){const [round,setRound]=useState(0);const [choice,setChoice]=useState<number|null>(null);const complete=round>=rounds.length;const current=rounds[Math.min(round,rounds.length-1)];const correct=choice===current.answer;return <MiniGameShell title="DESIGN THE CACHE" round={round} total={rounds.length} feedback={choice===null?undefined:correct?current.why:`That choice misses the workload's ownership or durability constraint. ${current.why}`} feedbackTone={choice===null?"neutral":correct?"success":"error"} feedbackSuccessLabel="PATTERN FITS ✓" complete={complete} completeTitle="CACHE ARCHITECTURES UNDERSTOOD" completeCopy="You selected cache ownership and write behavior from workload, freshness, and durability requirements—not from a favorite technology." onRestart={()=>{setRound(0);setChoice(null);}}><div className="strategy-scenario"><small>DESIGN ROUND {round+1}</small><h3>{current.title}</h3><p>Choose the behavior whose trade-off matches this system.</p></div><div className="game-choice-row">{current.options.map((option,index)=><button type="button" disabled={choice!==null} onClick={()=>setChoice(index)} key={option}>{option}</button>)}</div><div className="game-footer"><span/>{choice!==null?correct?<button type="button" className="lab-button" onClick={()=>{setRound(v=>v+1);setChoice(null);}}>{round===rounds.length-1?"FINISH":"NEXT DESIGN"}<ArrowRight/></button>:<button type="button" className="lab-button" onClick={()=>setChoice(null)}><Rotate/>TRY AGAIN</button>:null}</div></MiniGameShell>}
