"use client";

import { useState } from "react";
import { ArrowRight, Rotate } from "@/components/ui/icons";
import { MiniGameShell } from "@/components/ui/mini-game-shell";

type Asset="hero.jpg"|"app.js"|"product API"|"user dashboard"|"stock price";
const assets:{name:Asset;cache:string;policy:string}[]=[{name:"hero.jpg",cache:"EDGE FRIENDLY",policy:"Public, versionable, long TTL"},{name:"app.js",cache:"EDGE FRIENDLY",policy:"Use a hashed/versioned URL"},{name:"product API",cache:"POLICY DEPENDENT",policy:"Cache public responses by correct query key"},{name:"user dashboard",cache:"BYPASS / PRIVATE",policy:"Personalized; vary correctly or do not share"},{name:"stock price",cache:"VERY SHORT / STREAM",policy:"Freshness dominates; policy must be explicit"}];
export function CDNRequestLab(){const [asset,setAsset]=useState<Asset>("hero.jpg");const [warm,setWarm]=useState(false);const [edgeUp,setEdgeUp]=useState(true);const [originUp,setOriginUp]=useState(true);const item=assets.find(a=>a.name===asset)!;const hit=warm&&edgeUp;const available=hit||originUp;const latency=hit?22:edgeUp?198:originUp?235:0;const request=()=>{if(edgeUp&&originUp&&item.cache!=="BYPASS / PRIVATE")setWarm(true)};return <div className="cdn-lab lab-panel"><div className="lab-toolbar"><div><span className={available?"live-dot":"alert-dot"}/> EDGE REQUEST LAB <b>01</b></div><span>{hit?"EDGE HIT":available?"ORIGIN PATH":"UNAVAILABLE"}</span></div><div className="asset-tabs" role="tablist">{assets.map(a=><button type="button" role="tab" aria-selected={asset===a.name} onClick={()=>{setAsset(a.name);setWarm(false);}} key={a.name}>{a.name}</button>)}</div><div className="edge-topology"><div><small>USER</small><b>MUMBAI</b></div><ArrowRight/><div className={!edgeUp?"down":hit?"hit":""}><small>NEARBY EDGE</small><b>{edgeUp?hit?"HIT":"MISS":"OFFLINE"}</b><em>{edgeUp?"Mumbai PoP":"reroute"}</em></div><ArrowRight/><div className={!originUp?"down":""}><small>ORIGIN</small><b>{originUp?hit?"NOT CONTACTED":"US EAST":"OFFLINE"}</b></div></div><div className="cdn-result"><span><small>REQUEST</small><b>GET /{asset.replace(" ","-")}</b></span><span><small>POLICY</small><b>{item.cache}</b></span><span><small>SIMULATED LATENCY</small><b>{available?`~${latency} ms`:"FAILED"}</b></span></div><div className="lab-actions"><button type="button" onClick={request}>REQUEST ASSET</button><button type="button" onClick={()=>setWarm(false)}>PURGE EDGE</button><button type="button" className={!edgeUp?"danger":""} onClick={()=>setEdgeUp(v=>!v)}>{edgeUp?"FAIL EDGE":"RECOVER EDGE"}</button><button type="button" className={!originUp?"danger":""} onClick={()=>setOriginUp(v=>!v)}>{originUp?"FAIL ORIGIN":"RECOVER ORIGIN"}</button></div><div className="observation"><span>{hit&&!originUp?"VALID CACHED OBJECT SURVIVES ORIGIN FAILURE":hit?"NEARBY COPY":"CACHEABILITY IS POLICY"}</span><p>{hit&&!originUp?"The edge can continue serving a still-valid object while policy permits; misses cannot reach the unavailable origin.":item.policy} Timings are illustrative.</p></div></div>}

export function CDNInvalidationLab(){const [version,setVersion]=useState(1);const [edgeVersion,setEdgeVersion]=useState(1);const [strategy,setStrategy]=useState<"ttl"|"purge"|"version">("ttl");const publish=()=>setVersion(v=>v+1);const apply=()=>setEdgeVersion(version);return <div className="cdn-invalidation lab-panel"><div className="lab-toolbar"><div><span className={version===edgeVersion?"live-dot":"alert-dot"}/> EDGE INVALIDATION <b>02</b></div><span>{version===edgeVersion?"FRESH":"STALE EDGE"}</span></div><div className="version-stage"><div><small>ORIGIN</small><b>app.v{version}.js</b><em>latest release</em></div><ArrowRight/><div className={version!==edgeVersion?"stale":""}><small>EDGE COPY</small><b>app.v{edgeVersion}.js</b><em>{version===edgeVersion?"fresh":"still serving old bytes"}</em></div><ArrowRight/><div><small>USER RECEIVES</small><b>v{edgeVersion}</b></div></div><div className="strategy-tabs">{(["ttl","purge","version"] as const).map(id=><button type="button" aria-pressed={strategy===id} onClick={()=>setStrategy(id)} key={id}>{id==="ttl"?"WAIT FOR TTL":id==="purge"?"PURGE EDGE":"VERSIONED URL"}</button>)}</div><div className="lab-actions"><button type="button" onClick={publish}>PUBLISH NEW RELEASE</button><button type="button" onClick={apply}>{strategy==="ttl"?"ADVANCE TO EXPIRY":strategy==="purge"?"PURGE NOW":"REQUEST NEW URL"}</button><button type="button" onClick={()=>{setVersion(1);setEdgeVersion(1);}}><Rotate/>RESET</button></div><div className="observation"><span>{strategy.toUpperCase()}</span><p>{strategy==="ttl"?"The old object remains reusable until expiry, so shorter TTLs narrow the stale window at the cost of more origin validation.":strategy==="purge"?"Explicit invalidation asks edges to remove the old object; propagation is operational work, not instantaneous magic.":"A changed asset URL creates a new cache key, allowing immutable long-lived files without confusing old and new bytes."}</p></div></div>}

const rounds=[
 {title:"Global static images",options:["Origin only","Edge cache · long TTL","Private per-user cache"],answer:1,why:"Public, versionable images benefit from geographic edge copies and origin offload."},
 {title:"New JavaScript release",options:["Reuse app.js forever","Versioned asset URL","Cache personalized HTML globally"],answer:1,why:"A hashed or versioned URL creates a new key while old immutable assets can remain cached."},
 {title:"Personalized dashboard",options:["Shared cache by path only","Bypass shared cache","One response for every user"],answer:1,why:"Without a correct private/varying key, shared caching could expose another user's data."},
 {title:"Origin under viral load",options:["Edge caching + origin shield","Send every request to origin","Disable all TTLs"],answer:0,why:"Edges absorb repeated public content requests; a shield can collapse regional misses before origin."},
] as const;
export function ServeWorldGame(){const [round,setRound]=useState(0);const [choice,setChoice]=useState<number|null>(null);const complete=round>=rounds.length;const current=rounds[Math.min(round,rounds.length-1)];const correct=choice===current.answer;return <MiniGameShell title="SERVE THE WORLD" round={round} total={rounds.length} feedback={choice===null?undefined:correct?current.why:`That policy either wastes distance or risks incorrect sharing. ${current.why}`} feedbackTone={choice===null?"neutral":correct?"success":"error"} feedbackSuccessLabel="DELIVERY POLICY FITS ✓" complete={complete} completeTitle="EDGE DELIVERY UNDERSTOOD" completeCopy="You moved reusable public content closer while keeping personalized and freshness-sensitive responses governed by explicit cache keys." onRestart={()=>{setRound(0);setChoice(null);}}><div className="world-scenario"><small>GLOBAL ROUND {round+1}</small><h3>{current.title}</h3><div className="city-row"><span>MUMBAI</span><span>LONDON</span><span>SINGAPORE</span><span>SÃO PAULO</span><span>SYDNEY</span></div></div><div className="game-choice-row">{current.options.map((o,i)=><button type="button" disabled={choice!==null} onClick={()=>setChoice(i)} key={o}>{o}</button>)}</div><div className="game-footer"><span/>{choice!==null?correct?<button type="button" className="lab-button" onClick={()=>{setRound(v=>v+1);setChoice(null);}}>{round===rounds.length-1?"FINISH":"NEXT REGION"}<ArrowRight/></button>:<button type="button" className="lab-button" onClick={()=>setChoice(null)}><Rotate/>TRY AGAIN</button>:null}</div></MiniGameShell>}
