import type { Metadata } from "next";
import Link from "next/link";
import { ArrowDown, ArrowRight, MonitorIcon, ServerIcon, SparkIcon } from "@/components/ui/icons";
import { ConceptChain } from "@/components/lesson/concept-chain";
import { LessonPager } from "@/components/lesson/lesson-pager";
import { DeliverPageGame, HttpOnePressureLab, MultiplexingVisualizer, ProtocolComparison, ProtocolLoadLab, QuicLab, TcpHolDemo } from "@/components/labs/http-evolution-labs";
import { httpEvolutionLesson } from "@/content/http-evolution";
import { Reveal } from "@/components/ui/reveal";
import { SectionHeading } from "@/components/ui/section-heading";

export const metadata: Metadata = { title: "HTTP Evolution", description: "See why HTTP evolved from reusable HTTP/1.1 connections to HTTP/2 multiplexing and HTTP/3 over QUIC." };

const toc = [["01","Page load","#page-load"],["02","HTTP/1.1","#http1"],["03","HTTP/2","#http2"],["04","TCP loss","#tcp-loss"],["05","HTTP/3","#http3"],["06","Compare","#compare"],["07","Challenge","#challenge"]] as const;

export default function HttpEvolutionPage() {
  return (
    <article className="lesson-page evolution-page">
      <section className="evolution-hero page-shell">
        <div className="lesson-breadcrumb"><Link href="/#learning-map">Learning map</Link><span>/</span><b>Networking</b><span>/</span><span>Chapter 04</span></div>
        <ConceptChain current="04" />
        <div className="evolution-hero-grid">
          <div><p className="eyebrow"><span />PARALLEL DELIVERY · 26 MIN LAB</p><h1>One page.<br /><em>Many races.</em></h1><p className="lesson-deck">We can communicate securely. But a modern page needs many resources—and every network round trip, queue, and lost packet shapes when it becomes usable.</p><a className="text-link" href="#page-load">Load the page <ArrowDown /></a></div>
          <div className="resource-waterfall" aria-label="Webpage resources crossing several network lanes"><div className="waterfall-top"><MonitorIcon /><span><small>BROWSER REQUESTS</small><b>systemlab.dev</b></span><em>6 ASSETS</em></div>{httpEvolutionLesson.assets.map(([name,size,id],index) => <div className={`waterfall-row waterfall-row--${id}`} key={id}><small>{String(index + 1).padStart(2,"0")}</small><b>{name}</b><i><span /></i><code>{size}</code></div>)}<div className="waterfall-question">What happens when every resource must cross the network efficiently?</div></div>
        </div>
      </section>

      <nav className="chapter-nav" aria-label="Chapter sections"><div className="page-shell"><span>CHAPTER 04</span><div>{toc.map(([number,label,href]) => <a href={href} key={number}><small>{number}</small>{label}</a>)}</div></div></nav>

      <section className="lesson-section page-shell" id="page-load"><Reveal><SectionHeading eyebrow="01 · WHY EVOLUTION HAPPENED" title="A webpage is a delivery problem." copy="HTML discovers CSS, scripts, fonts, images, and third-party work. HTTP kept its request/response meaning while each generation changed how those messages share connections and recover from network pressure." /></Reveal><div className="resource-story"><div><span>READ IT</span><h3>Six resources. Different sizes. One page.</h3><p>The protocol must use available connections without letting setup, sequencing, or loss dominate the critical path.</p></div><ArrowRight /><div><span>SEE IT</span><code>index.html · styles.css · app.js · hero.jpg · avatar.jpg · analytics.js</code></div></div><Reveal delay={0.08}><ProtocolLoadLab /></Reveal></section>

      <section className="lesson-section lesson-section--wide evolution-h1-section" id="http1"><div className="page-shell"><Reveal><SectionHeading eyebrow="02 · HTTP/1.1" title="Reuse connections. Open several lanes." copy="HTTP/1.1 persistent connections avoid reconnecting for every object. Browsers also opened a limited set of parallel TCP connections per origin because each connection generally handled response work in order." /></Reveal><div className="h1-definition-grid"><div><span>KEEP-ALIVE</span><h3>Reuse the lane</h3><p>Another request can use an existing TCP connection after the previous exchange, avoiding repeated setup.</p></div><div><span>PARALLEL CONNECTIONS</span><h3>Add lanes</h3><p>Several connections prevent one response from blocking every resource globally, but each lane adds handshake and congestion state.</p></div><div><span>PIPELINING</span><h3>Rare in practice</h3><p>Requests could be sent without waiting, but responses still had to arrive in order and intermediaries supported it inconsistently.</p></div></div><Reveal delay={0.08}><HttpOnePressureLab /></Reveal></div></section>

      <section className="lesson-section page-shell" id="http2"><Reveal><SectionHeading eyebrow="03 · HTTP/2" title="One connection. Many logical streams." copy="HTTP/2 splits messages into binary frames tagged by stream. Frames can interleave, so a slow response no longer has to occupy the HTTP application lane before another response advances." /></Reveal><div className="h2-stack"><div><b>HTTP/2</b><small>requests + responses</small></div><ArrowDown /><div><b>BINARY FRAMES</b><small>stream IDs interleave</small></div><ArrowDown /><div><b>ONE TLS + TCP CONNECTION</b><small>shared congestion and ordered bytes</small></div></div><div className="h2-features"><div><span>01</span><b>Multiplexing</b><p>Concurrent request/response streams share a connection.</p></div><div><span>02</span><b>Header compression</b><p>HPACK reduces repeated header representation.</p></div><div><span>03</span><b>Single connection efficiency</b><p>Fewer handshakes and one congestion-control context.</p></div></div><Reveal delay={0.08}><MultiplexingVisualizer /></Reveal></section>

      <section className="lesson-section lesson-section--wide hol-section" id="tcp-loss"><div className="page-shell"><Reveal><SectionHeading eyebrow="04 · BREAK HTTP/2" title="Multiplexed above. Ordered below." copy="HTTP/2 removes application-level response sequencing between streams, but every frame still becomes bytes in one ordered TCP stream. Lose a TCP segment and later bytes wait for retransmission." /></Reveal><Reveal delay={0.08}><TcpHolDemo /></Reveal></div></section>

      <section className="lesson-section page-shell" id="http3"><Reveal><SectionHeading eyebrow="05 · HTTP/3 + QUIC" title="Stop making unrelated streams share one delivery gap." copy="HTTP/3 maps HTTP semantics onto QUIC. QUIC uses UDP as a substrate, then implements secure connection setup, reliability, congestion control, and independent transport streams in user space." /></Reveal><div className="transport-stack-compare"><div><span>HTTP/2</span><b>HTTP</b><i>↓</i><b>TLS</b><i>↓</i><b>TCP</b><i>↓</i><b>IP</b></div><div><span>HTTP/3</span><b>HTTP</b><i>↓</i><b className="quic-block">QUIC <small>streams · TLS 1.3 · transport</small></b><i>↓</i><b>UDP</b><i>↓</i><b>IP</b></div></div><Reveal delay={0.08}><QuicLab /></Reveal><div className="user-space-note"><SparkIcon /><div><span>WHY DIDN’T WE JUST FIX TCP?</span><p>Changing TCP behavior across operating-system kernels, middleboxes, and deployed infrastructure is slow. QUIC can evolve in application/user space while using UDP to traverse the network—but it still must implement responsible reliability and congestion control.</p></div></div></section>

      <section className="lesson-section lesson-section--wide" id="compare"><div className="page-shell"><Reveal><SectionHeading eyebrow="06 · COMPARE THE MODELS" title="Newer is a different set of trade-offs—not a universal trophy." copy="Compare transport behavior, then challenge the shortcuts that make protocol evolution sound simpler than it is." /></Reveal><Reveal delay={0.08}><ProtocolComparison /></Reveal><div className="misconception-grid">{httpEvolutionLesson.misconceptions.map(([claim,truth],index) => <div key={claim}><span>MISCONCEPTION {String(index + 1).padStart(2,"0")}</span><h3>“{claim}”</h3><p>{truth}</p></div>)}</div></div></section>

      <section className="lesson-section delivery-game-section" id="challenge"><div className="page-shell"><Reveal><SectionHeading eyebrow="07 · APPLY IT" title="Deliver the page." copy="Match protocol behavior to simultaneous assets, packet loss, network migration, and a legacy environment. The newest protocol is not automatically the correct explanation." /></Reveal><Reveal delay={0.08}><DeliverPageGame /></Reveal></div></section>

      <section className="takeaway-section"><div className="page-shell"><Reveal><SectionHeading eyebrow="HTTP EVOLUTION SUMMARY" title="More lanes. Shared lanes. Independent lanes." /></Reveal><div className="evolution-summary-flow">{httpEvolutionLesson.summary.map(([term,note],index) => <div key={term}><span>0{index + 1}</span><h3>{term}</h3><p>{note}</p>{index < httpEvolutionLesson.summary.length - 1 ? <ArrowRight /> : null}</div>)}</div><div className="source-note"><span>SOURCE MAPPING</span><p>Derived from <a href="https://github.com/ChetanAmritanshu/High-Level-Design/blob/main/04_HTTP_Evolution_HTTP_1_1_HTTP_2_HTTP_3_QUIC.docx" target="_blank" rel="noreferrer"><code>{httpEvolutionLesson.source}</code></a>. The source establishes connection reuse, HTTP/2 streams, TCP head-of-line blocking, QUIC streams, faster setup, and the HTTP/1.1 → HTTP/2 → HTTP/3 progression.</p></div><LessonPager previous={{ number:"03", title:"HTTP, HTTPS & TLS", href:"/learn/http-https-tls" }} next={{ number:"05", title:"Real-Time Communication", href:"/learn/realtime-communication", copy:"How do polling, SSE, and WebSockets keep information moving?" }} /><Link className="back-to-map" href="/#learning-map"><ServerIcon /> Return to the learning map <ArrowRight /></Link></div></section>
    </article>
  );
}
