import type { Metadata } from "next";
import Link from "next/link";
import { ArrowDown, ArrowRight, DatabaseIcon, ServerIcon } from "@/components/ui/icons";
import { ConceptChain } from "@/components/lesson/concept-chain";
import { LessonPager } from "@/components/lesson/lesson-pager";
import { BreakCache, CacheLab, HitRatioLab, SaveDatabaseGame } from "@/components/labs/cache-labs";
import { Reveal } from "@/components/ui/reveal";
import { SectionHeading } from "@/components/ui/section-heading";

export const metadata: Metadata={title:"Caching Fundamentals",description:"Explore cache hits, misses, TTL, locality, freshness, and downstream pressure through interactive simulations."};
const toc=[["01","Repeat work","#repeat"],["02","Hit / miss","#hit-miss"],["03","Hit ratio","#ratio"],["04","Freshness","#freshness"],["05","Challenge","#challenge"]] as const;
const cacheCandidates = [
  ["Static product catalog","High reuse · tolerates bounded staleness","Strong candidate"],
  ["User session","Frequently read · correctness sensitive","Cache carefully"],
  ["Search results","Expensive · query-dependent","Useful with short TTL"],
  ["Stock price","Highly volatile","Very short TTL / stream"],
  ["Bank balance","Correctness critical","Verify authoritative state"],
  ["Profile image","Read-heavy · versionable","Strong candidate"],
] as const;
export default function CachingPage(){return <article className="lesson-page caching-page"><section className="caching-hero page-shell"><div className="lesson-breadcrumb"><Link href="/#learning-map">Learning map</Link><span>/</span><b>Performance</b><span>/</span><span>Chapter 08</span></div><ConceptChain current="08"/><div className="topic-hero-grid"><div><p className="eyebrow"><span/>FAST PATHS · 28 MIN LAB</p><h1>Remember work.<br/><em>Respect freshness.</em></h1><p className="lesson-deck">Caches make repeated reads fast by keeping useful copies nearby. Every copy also creates a question: when is it too old to trust?</p><a className="text-link" href="#repeat">Request product:42 <ArrowDown/></a></div><div className="cache-hero-card"><code>GET /products/42</code>{[1,2,3].map((run)=><div key={run}><span>REQUEST {run}</span><i/><b>DATABASE QUERY</b><em>240 ms</em></div>)}<strong>Why fetch the same answer again?</strong></div></div></section><nav className="chapter-nav" aria-label="Chapter sections"><div className="page-shell"><span>CHAPTER 08</span><div>{toc.map(([n,l,h])=><a href={h} key={n}><small>{n}</small>{l}</a>)}</div></div></nav>
<section className="lesson-section page-shell" id="repeat"><Reveal><SectionHeading eyebrow="01 · THE REPEATED COST" title="Locality makes memory useful." copy="Temporal locality means the same data is likely to be requested again soon. Spatial locality means nearby or related data may be used together. A cache exploits those patterns—when they actually exist."/></Reveal><div className="latency-ladder"><div><span>CACHE HIT</span><b>4 ms</b><i><em style={{width:"8%"}}/></i><p>Nearby reusable copy</p></div><div><span>DATABASE</span><b>180 ms</b><i><em style={{width:"75%"}}/></i><p>Authoritative query</p></div><div><span>REMOTE ORIGIN</span><b>240 ms</b><i><em style={{width:"100%"}}/></i><p>Network + compute</p></div></div><p className="illustrative-note">Illustrative deterministic values show relative paths, not production benchmarks.</p></section>
<section className="lesson-section lesson-section--wide" id="hit-miss"><div className="page-shell"><Reveal><SectionHeading eyebrow="02 · PLAY WITH IT" title="A miss fills the fast path." copy="Request keys repeatedly, advance simulated time, and watch the cache populate, hit, expire, and return to the authoritative database."/></Reveal><Reveal delay={0.08}><CacheLab/></Reveal></div></section>
<section className="lesson-section page-shell" id="ratio"><Reveal><SectionHeading eyebrow="03 · HIT RATIO" title="The workload decides whether caching pays." copy="A repeated hot key can produce a high hit ratio with little memory. Random one-off access can leave the same cache mostly ineffective."/></Reveal><Reveal delay={0.08}><HitRatioLab/></Reveal><div className="cache-layer-stack"><span>BROWSER CACHE</span><ArrowDown/><span>CDN</span><ArrowDown/><span>REVERSE PROXY CACHE</span><ArrowDown/><span>APPLICATION / DISTRIBUTED CACHE</span><ArrowDown/><span>DATABASE · ORIGIN</span></div><p className="illustrative-note">Caches can exist at many layers. CDN behavior is introduced here only as a location; edge delivery has its own later lesson.</p></section>
<section className="lesson-section lesson-section--wide" id="freshness"><div className="page-shell"><Reveal><SectionHeading eyebrow="04 · BREAK THE FAST PATH" title="A copy can be absent, old, or unavailable." copy="TTL bounds how long an entry may be reused, but expiration and outages shift work back to the database—and stale data can exist before the timer ends."/></Reveal><Reveal delay={0.08}><BreakCache/></Reveal><div className="cache-candidate-grid">{cacheCandidates.map(([name,signal,verdict])=><div key={name}><DatabaseIcon/><h3>{name}</h3><p>{signal}</p><b>{verdict}</b></div>)}</div></div></section>
<section className="lesson-section page-shell" id="challenge"><Reveal><SectionHeading eyebrow="05 · APPLY IT" title="Save the database." copy="Configure selective caching and TTL under three traffic models. More hits are useful only when the freshness trade-off remains acceptable."/></Reveal><Reveal delay={0.08}><SaveDatabaseGame/></Reveal></section>
<section className="takeaway-section"><div className="page-shell"><Reveal><SectionHeading eyebrow="CACHING SUMMARY" title="Fast copies need explicit freshness."/></Reveal><div className="topic-summary-grid"><div><span>01</span><b>Hit</b><p>A valid nearby copy returns quickly.</p></div><div><span>02</span><b>Miss</b><p>Read the source and populate the cache.</p></div><div><span>03</span><b>TTL</b><p>Limits how long the copy may be reused.</p></div><div><span>04</span><b>Trade-off</b><p>Hits reduce load; longer reuse risks staleness.</p></div></div><div className="source-note"><span>SOURCE MAPPING</span><p>Derived from <a href="https://github.com/ChetanAmritanshu/High-Level-Design/blob/main/08_Caching_Fundamentals.docx" target="_blank" rel="noreferrer"><code>08_Caching_Fundamentals.docx</code></a>. The source establishes latency hierarchy, temporal and spatial locality, hit/miss semantics, hit ratio, TTL, and memory-versus-freshness trade-offs.</p></div><LessonPager previous={{number:"07",title:"Reverse Proxy & API Gateway",href:"/learn/reverse-proxy-api-gateway"}} next={{number:"09",title:"Cache Architectures & Redis",href:"/learn/cache-architectures-redis",copy:"Choose where cache lives and who keeps it synchronized."}}/><Link className="back-to-map" href="/#learning-map"><ServerIcon/> Return to the learning map <ArrowRight/></Link></div></section></article>}
